name: Check for Dead Links
on:
   push:
    branches:
    - test    
jobs:
  copy-files:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Run the test
      run: |
         echo Hello, world

