name: Check for Dead Links
on: push
jobs:
  check-links:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Run the test
      run: |
         cd $GITHUB_WORKSPACE
         yarn
         yarn check-md
